# ruby=2.1
# gemset=ora_config
source 'http://rubygems.org'

group :test do
  gem 'wwtd'
  gem 'rake'
  gem 'puppet', ENV['PUPPET_GEM_VERSION'] || '~> 4.8.0'
  gem 'puppet-lint'
  gem 'rspec-puppet'
  gem 'puppet-syntax'
  gem 'puppetlabs_spec_helper'
  gem 'librarian-puppet'
  gem 'easy_type_helpers', git: 'https://github.com/enterprisemodules/easy_type_helpers.git'
end

group :development do
  gem 'byebug'
  gem 'rubocop'
  gem 'pry'
  gem 'pry-byebug'
  gem 'travis'
  gem 'travis-lint'
  gem 'beaker'
  gem 'beaker-rspec'
  gem 'puppet-blacksmith'
end
